### PR TITLE
feat: add icons

### PR DESCRIPTION
**Pull request by manuelduarte077**
I installed the plugins in Android Studio, but I don't get the icon for dart and kotlin but that adds the 2 icons

- [x] icon for .dat files
- [x] icon for kotlin .kt files

Screenshot_48

Greetings :)

### CODE REVIEW

**Comment by manuelduarte077** [comment]
add the php icon but then remove it, but the commit failed 😅

**Comment by jonathanlermitage** [comment]
Thx!

One thing about Kotlin files: JetBrains IDEs offer Kotlin support for free: `.kt` files are already supported.  
Adding support of kt files in Extra Icons would override icons of regular Kotlin files, and Kotlin Enums and Kotlin Interfaces (you can previews icons here: https://jetbrains.design/intellij/resources/icons_list/ filter by 'kotlin').  

As an alternative, I could reproduce what I am doing in [intellij-extra-toolwindow-colorful-icons plugin](https://github.com/jonathanlermitage/intellij-extra-toolwindow-colorful-icons) -> instead of overriding icons by file names, we would override icons by icon names. I mean, we will override the Kotlin icon, not the icon of `.kt` files. We could do the same thing for Kotlin Interface and Kotlin Enum icons.  
If you are OK, you can remove the Kotlin icon, keep the Dart icon, and I will implement icons overriding.

**Comment by manuelduarte077** [comment]
I understand, if you are right, I did not realize, in fact if I tried to put the icon of php the blade for laravel, and the other files of php classes, php test, but I do not take any because I put them all like the one from php.

ok then I'll just drop the dart

Thank you very much for the clarification 💯

**Comment by jonathanlermitage** [comment]
You're welcome :)

I just implemented IDE icons overriding by icon name. You can see an example here: https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/ide203/src/main/java/lermitage/intellij/extra/icons/ExtraIconProvider.java#L32 -> replaced the Kotlin Gradle script icon (`kotlin_gradle_script.svg`, you can find this name [here](https://jetbrains.design/intellij/resources/icons_list/)) by `/extra-icons/gradle_kotlin_colored.svg`.

**Comment by manuelduarte077** [comment]
Hello we are again
Remove icon for kotlin, leave the dart, add icon for files ending with .yaml, .look, and .html

Screenshot_29

these icons appear in flutter projects

**Pull request closed without merging**
