### PR TITLE
Configured Gradle

### LINKED ISSUE #11: Gradle vs Devkit
I was looking at the [getting started page for creating IntelliJ plugins](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html) and it mentions two workflows, one using DevKit, and one using Gradle. Since this project does not have any Gradle files, I assume it using the old DevKit workflow.

Would it be beneficial to upgrade to using Gradle?

### PR DESCRIPTION
**Pull request by MatthiasKunnen**
I've made a number of changes:

- ~Changed package group and structure as it did not meet [package naming conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)~
  ```diff
  - lermitage.intellij.extra.icons
  + com.github.jonathanlermitage.intellij.extra_icons
  ```
- Added .editorconfig file and formatted sources
- Implemented `SettingsForm.getHelpTopic()` as it was required
- Configured Gradle

**Note**
I didn't find any code that requires Sass or JavaScript support as the [README](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/da016e12e3cfb3320bfa529e7ef8bb8e6c6e7ec9/README.md) states. If those are required after all I need to add them.

Let me know what you think and if something needs changing.

Closes #11.

### CODE REVIEW

**Comment by jonathanlermitage** [comment]
Thx a lot!

I would lie to keep the `lermitage.intellij.extra.icons` package, because I don't want to link this project to GitHub. I usually host projects on multiple hosting providers like GitLab, Framagit, etc.

I am testing the Gradle build, and adding some comments in the PR.  

I am also facing a problem with generated plugin (`buildPlugin` task): the generated `plugin.xml` defines supported IDE version like this: `<idea-version since-build="183.4284" until-build="183.*"/>` -> that means plugin is incompatible with IJ 2019. Expected version should be `<idea-version since-build="183.0"/>`. 
I hope this is not a Gradle IntelliJ plugin limitation, because plugins like Lombok or Gauge regularly have to update version range -> this is very annoying. I'll ask some help to JetBrains.
If there's no solution, I will maintain two branches: a Gradle branch dedicated to contributors, and a classical branch for releases. I'll only have to cherrypick changes (I already do this for the ide173 branch).

Except this issue, Gradle build and generated plugin work like a charm! 👍 .

**Comment by MatthiasKunnen** [comment]
I'll have a look at the buildPlugin task.

About the package name, it does not have to start with `com.github`, that's just to make it unique. As the [package naming conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) state, the first part must be a top level domain, and the second part must be a domain that you own. In the case of `com.github.jonathanlermitage` you own the subdomain. Every part must represent something more specific, that's why I changed `extra.icons` to `extra_icons`.

Another option would be: `com.gmail.jonathanlermitage.intellij.extra_icons` as you own that email address.

**Comment by jonathanlermitage** [comment]
I usually look at both Sun and Google conventions but, sometimes, I simply want to try something new. [Project Lombok](https://projectlombok.org/) defines the `lombok` package name only, and I like this idea (okay, this example is a bit extreme ^_^, but I don't like very package names).  
Since Extra Icons plugin is not a library, and there's no chance to see an other developer called Lermitage, I think we can use a short package name.  
Lastly, I wont include my email because I planned to leave Google/Gmail :-D

**Comment by MatthiasKunnen** [comment]
Okido,  you want `extra.icons` or `extra_icons`?

I've also fixed the buildPlugin task

**Comment by jonathanlermitage** [comment]
Nice!

Sun convention says "extra_icons" but Google says "extra.icons". I have no preference, so I suggest to keep "extra.icons" in order to limit changes.

**Comment by MatthiasKunnen** [comment]
All done

**Comment by jonathanlermitage** [comment]
Thx a lot! Will be merged asap.

**Pull request merged**
